### ISSUE TITLE
Error: connection to partner 'localhost:3200' broken

### ISSUE THREAD

**Issue by ecostella2010** [nzamani/sap-nw-abap-trial-docker#2]
Hi,

I have the following issue in sap gui for java mac:

Connection closed
Error: connection to partner 'localhost:3200' broken
Thu Feb 28 18:32:28 2019
Release 753
Component NI (network interface), version 40
rc = -6, module
/net/usr.delivery/SAPGUIForJava_750_REL/bas_753_REL/src/base/ni/nixxi.cpp,
line 5173
Detail NiIRead: P=127.0.0.1:3200; L=127.0.0.1:55510
System Call recv

Reviewed the ports in the container:
vhcalnplci:/var/tmp/NW752 # nmap 172.17.0.3 -p 3200 

Starting Nmap 6.47 ( http://nmap.org ) at 2019-02-28 21:16 UTC
Nmap scan report for vhcalnplci (172.17.0.3)
Host is up (0.00011s latency).
PORT     STATE  SERVICE
3200/tcp closed tick-port

Also in the host local:
bash-3.2$ nmap localhost -p  3200
Starting Nmap 7.70 ( https://nmap.org ) at 2019-02-28 22:11 -03
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00031s latency).
Other addresses for localhost (not scanned): ::1

PORT     STATE SERVICE
3200/tcp open  tick-port

Nmap done: 1 IP address (1 host up) scanned in 0.06 seconds
bash-3.2$ 

Can you help me, please?

**Comment by nzamani** [comment]
I'm afraid telling you this issue is not related to this repo at all. It's nothing I can change/fix with a commit pushed to Github. Thus, I'll have to close this issue - sorry for that.

However, I suggest you to post a question on the SAP Community. Make sure to post a real question instead of adding a comment to the blog I wrote (you may link the blog though). This way you'll get help from the community.

**Comment by saikrishnasuper** [comment]
Hi nzamani,


Please help me out , I am also facing the same issue.
